kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test ./...
  - go build .

trigger:
  branch:
    include:
    - main
  event:
    include:
    - push
    - pull_request

