version: '3.7'
services:
  web:
    build: .
    ports:
    - "4000"

  nginx:
    image: "nginx:alpine"
    volumes:
    - "./nginx:/etc/nginx/conf.d"
    ports:
    - "8090:80"
    depends_on:
    - "web"
